"""empty message

Revision ID: 8b9d28e8b9f5
Revises: ef8a7e184062
Create Date: 2020-01-12 15:54:15.509104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9d28e8b9f5'
down_revision = 'ef8a7e184062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garbagetype', sa.Column('typename', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'garbagetype', ['typename'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'garbagetype', type_='unique')
    op.drop_column('garbagetype', 'typename')
    # ### end Alembic commands ###
